### ISSUE TITLE
load banner error 

### ISSUE THREAD

**Issue by syrakozz** [tapdaq/tapdaq-android-samples#2]
im getting 
   java.lang.NoSuchMethodError: No virtual method load(Landroid/app/Activity;Lcom/tapdaq/sdk/model/TMAdSize;Lcom/tapdaq/sdk/listeners/TMAdListener;)V in class Lcom/tapdaq/sdk/TMBannerAdView; or its super classes (declaration of 'com.tapdaq.sdk.TMBannerAdView' appears in /data/app/com.testingapp-pHycge4MOzl-cNJCaLiJaw==/base.apk!classes3.dex)
        at com.rn.tapdaq.RNTapdaqModule$4.run(RNTapdaqModule.java:330)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)

when load banner

**Comment by rdominic** [comment]
Apologies we couldn't help here. Tapdaq is being deprecated and it's services turned off.
All public SDK repo's will be archived shortly and changed to private later this year.

For an alternative mediation platform we recommend IronSource.

Closing this ticket.
