### ISSUE TITLE
Error: 140 - Empty Waterfall

### ISSUE THREAD

**Issue by aiviapp** [tapdaq/tapdaq-android-samples#4]
I use this SDK to display Facebook ads, but I got an error: "140 - Empty Waterfall".

**Comment by rdominic** [comment]
Apologies we couldn't help here. Unfortunately Tapdaq is being deprecated and its services turned off.
All public SDK repo's will be archived shortly and changed to private later this year.

For an alternative mediation platform we recommend IronSource.

Closing this ticket.
